# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - persist_to_workspace:
          root: ~/repo
          paths: ./*
      - run: pwd
      - run: ls

  regain_workspace:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    
    - attach_workspace:
        at: ~/repo
    - run: pwd
    - run: ls

workflows:
  version: 2

  test:
    jobs:
      - build
      - regain_workspace:
          requires:
            - build
